name: flutter_tts_workspace
environment:
  sdk: ">=3.9.0 <4.0.0"
dev_dependencies:
  melos: ^7.3.0
  path: ^1.9.1
  pigeon: ^26.1.0
workspace:
  - apps/example
  - packages/flutter_tts
  - packages/flutter_tts_android
  - packages/flutter_tts_macos
  - packages/flutter_tts_ios
  - packages/flutter_tts_platform_interface
  - packages/flutter_tts_web
  - packages/flutter_tts_windows
melos:
  scripts:
    gen_pigeon:
      run: dart run tools/generate_pigeons.dart
