name: flutter_tts
description: A flutter plugin for Text to Speech.  This plugin is supported on iOS, Android, & Web.
version: 1.2.1
homepage: https://github.com/dlutton/flutter_tts

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tundralabs.fluttertts
        pluginClass: FlutterTtsPlugin
      ios:
        pluginClass: FlutterTtsPlugin
      web:
        pluginClass: FlutterTtsPlugin
        fileName: flutter_tts_web.dart

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
