name: flutter_tts
description: A flutter plugin for Text to Speech.  This plugin is supported on iOS, Android, Web, & macOS.
version: 3.0.0
homepage: https://github.com/dlutton/flutter_tts

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tundralabs.fluttertts
        pluginClass: FlutterTtsPlugin
      ios:
        pluginClass: FlutterTtsPlugin
      macos:
        pluginClass: FlutterTtsPlugin
      web:
        pluginClass: FlutterTtsPlugin
        fileName: flutter_tts_web.dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.22.0'
