name: flutter_tts_ios
description: A flutter plugin for Text to Speech.  This plugin is supported on iOS, macOS, Android, Web, & Windows.
version: 5.0.0
homepage: https://github.com/dlutton/flutter_tts
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_tts_platform_interface: ^5.0.0
  multiple_result: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0

flutter:
  plugin:
    implements: flutter_tts
    platforms:
      ios:
        pluginClass: FlutterTtsPlugin
        dartPluginClass: FlutterTtsIos
